### ISSUE TITLE
jMMM in farsi

### ISSUE THREAD

**Issue by alighasemzadeh** [fingerpich/vue-jalali-moment#2]
Hello,
How can I set locale farsi in vue??

**Comment by fingerpich** [comment]
Please follow this link [vue-jalali-moment](https://github.com/fingerpich/vue-jalali-moment)
hope it helps you

**Comment by alighasemzadeh** [comment]
@fingerpich not work for me.

**Comment by fingerpich** [comment]
Please create a demo in stackblitz then everyone could help you.

**Comment by alighasemzadeh** [comment]
@fingerpich 
سلام
فکر می کنم واضح مشکل شما راهنمایی درستی در این مورد نداشتید.

**Comment by fingerpich** [comment]
I don't know what is the problem,
when you create a demo some of problems will solve automatically
please create a demo and share it with us

**Comment by alighasemzadeh** [comment]
@fingerpich 
سلام
من دارم از کد زیر برای نمایش فارسی استفاده می کنم
`{{ message.created_at | moment("jD jMMMM,jYYYY HH:mm") }}`
اسم ماه را به صورت انگلیسی نمایش می دهد یعنی  خرداد را می نویسد
Khordad
باید بنویسه
خرداد.

**Comment by fingerpich** [comment]
Please take a look at the [demo in stackblitz](https://stackblitz.com/edit/vue-jggp6l).

**Comment by alighasemzadeh** [comment]
@fingerpich 
الان فارسی شد ولی درست نشون نمی دهد
1- سال را میلادی می زنه
2-ماه را اشتباه می زنه

**Comment by matinwd** [comment]
I have same here. still shows date wrong

**Comment by pouyaGit** [comment]
any way to show jMMMM in persian instead of finglish yet?
